// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0TRzF9ygqf61tsQuoTWFD0q1VDJNnvlU',
    appId: '1:958739409259:web:2a57dad7726549f48d442e',
    messagingSenderId: '958739409259',
    projectId: 'chat-app-9a76e',
    authDomain: 'chat-app-9a76e.firebaseapp.com',
    storageBucket: 'chat-app-9a76e.appspot.com',
    measurementId: 'G-3WX6JV2L5G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtHscNugLJWZVko6fpoS4xfetonucBH2Y',
    appId: '1:958739409259:android:0d0b9353ce2c94798d442e',
    messagingSenderId: '958739409259',
    projectId: 'chat-app-9a76e',
    storageBucket: 'chat-app-9a76e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlPzQGfqOG7aw6rbGICgwQ4HJtrctlqYQ',
    appId: '1:958739409259:ios:1207f3b8ef0ade148d442e',
    messagingSenderId: '958739409259',
    projectId: 'chat-app-9a76e',
    storageBucket: 'chat-app-9a76e.appspot.com',
    iosBundleId: 'com.example.chattApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlPzQGfqOG7aw6rbGICgwQ4HJtrctlqYQ',
    appId: '1:958739409259:ios:dadc31bd9383d9478d442e',
    messagingSenderId: '958739409259',
    projectId: 'chat-app-9a76e',
    storageBucket: 'chat-app-9a76e.appspot.com',
    iosBundleId: 'com.example.chattApp.RunnerTests',
  );
}
